### ISSUE TITLE
Call of cron.php

### ISSUE THREAD

**Issue by pate313373** [Super-Visions/docker-itop#12]
Hi,

thanks for this nice image!
I'm just wondering if I have to call cron.php manually or if it's scheduled in your image?
If required, do you have any recommendation how to call it?

Currently my way to solve this is a docker health check.

````
version: '3.9'

services:
  db:
    image: mariadb:11.1.2
    volumes:
      - ./mysqlData:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: superSecretAdmin
      MYSQL_DATABASE: itop
      MYSQL_USER: itop
      MYSQL_PASSWORD: itop
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"
      interval: 20s
      timeout: 20s
      retries: 10
  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
  itop:
    depends_on:
      db:
        condition: service_healthy
    image: supervisions/itop:3.1.0
    restart: unless-stopped
    volumes:
      - ./itop-conf:/var/www/html/conf
      - ./itop-data:/var/www/html/data
      - ./itop-env:/var/www/html/env-production
      - ./itop-log:/var/www/html/log
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 80:80
    environment:
      DB_ENV_MYSQL_USER: itop
      DB_ENV_MYSQL_PASSWORD: itop
      DB_ENV_MYSQL_DATABASE: itop
    # disable healthcheck for setup
    healthcheck:
      test: "php webservices/cron.php --auth_user=admin --auth_pwd=admin"
      interval: 1600s
      timeout: 1200s
      retries: 5
      
# helpful commands
# docker ps
# docker inspect --format "{{json .State.Health }}" CONTAINER_ID
# winpty docker exec -it CONTAINER_ID bash
````

Many thanks

PS: I have noticed, that there is no example for docker-compose in the documentation. It took me a few hours to figure out which volumes and ENV were required. Feel free to put it in the docs.

**Comment by Hipska** [comment]
As the [documentation states](https://github.com/Super-Visions/docker-itop#scheduling-cronphp), the cron.php is not scheduled by this image.

I'm not sure the health check is a good place to add this, as the cron will stop when for example doing a setup, and thus the container might get stopped/restarted?

Best way is to have another container specifically running this command.

Edit: Sorry for the late reply, I missed the notification of this issue.

> PS: I have noticed, that there is no example for docker-compose in the documentation. It took me a few hours to figure out which volumes and ENV were required. Feel free to put it in the docs.

Indeed, feel free to add this in the docs with a new PR.

**Comment by joaquinvacas** [comment]
So let me ask... If I understand correctly... does this mean that cron.php has to be manually invoked?

I'm running iTop on an Azure Container App environment and that's a difficult thing to do.

**Comment by Hipska** [comment]
It has to be invoked manually indeed. We (and @Combodo) advise to run iTop in Azure on a [Linux Virtual Machine](https://azure.microsoft.com/en-gb/products/virtual-machines/) to have all you need and full support. Also then you can add additional stuff like various [data collectors](https://store.itophub.io/en_US/taxons/all-extensions?criteria%5Bsearch%5D%5Bvalue%5D=collector) added and running as well..
