### ISSUE TITLE
Volume mapping does not support the toolkit

### ISSUE THREAD

**Issue by pate313373** [Super-Visions/docker-itop#13]
Hi,

I'd rather like to be able to map /var/www/html as a whole, because the current volume setup does not allow to deploy extensions and the toolkit itself... :(

Kind regards

**Comment by pate313373** [comment]
I've created a pull request #14 which implements my suggested solution.

**Comment by Hipska** [comment]
Yes, you can add extensions by mounting them as usual:

```shell
docker run -d -p 80:80 --name=my-itop -v ./toolkit:/var/www/html/toolkit -v ./my-extension:/var/www/html/extensions/my-extension supervisions/itop:latest 
```

It is a very bad idea to try to mount `/var/www/html` as a volume, as that will make upgrades very difficult. That is why I created volumes for the essential directories (data, env, log, ..)

**Comment by pate313373** [comment]
Could you elaborate why it's a bad idea?

**Comment by Hipska** [comment]
As then you completely decouple the iTop source code files from the image/container. When you later want to update the container to a newer version of iTop, then it will not do anything as the code is already copied to your volume, and thus updating the image will have no effect.

If you really want to do this, I would advise to just run a plain `php:apache` container and mount the iTop code manually.
