### ISSUE TITLE
Extension installation

### ISSUE THREAD

**Issue by rvmadeit** [Super-Visions/docker-itop#15]
hi, 
How can we install extension, I try, but it keeps sending me back to my instance without installing it. Can we install an extension manually ?

**Comment by Hipska** [comment]
Yes it is sure possible to install extensions. What do you mean with "it keeps sending me back"?

**Comment by Hipska** [comment]
@rvmadeit Do you have any feedback? Without, I will need to close this issue..

**Comment by joaquinvacas** [comment]
Hi!

I'm having the same issue.

What @rvmadeit wanted to mean (I think) is that you can access to iTop Hub, it does recognize your instance but doesn't install a thing, it just redirects to your instance's URL but nothing else happens, no extension install or anything else.
That's the issue I'm having.


Alternatively, I tried mounting the extension volume separately and added the uncompressed folder for each extension.

It seems like those are recognized by iTop but don't seem to be loaded, as those are not working.

![Image](https://github.com/user-attachments/assets/55766b5a-2338-4d0b-8c5b-50b0cd3e8e2e)

Container is running on Azure Container Apps, everything else seems to be working fine but not the extensions themselves.

**Comment by rvmadeit** [comment]
Hi, I stop using itop but when I run mine on a docker container on a linux, you need to copy the extension that you download and paste it to the docker container (eg with docker the command is : docker cp /host/path/target containerId:/file/path/within/container )

**Comment by joaquinvacas** [comment]
> Hi, I stop using itop but when I run mine on a docker container on a linux, you need to copy the extension that you download and paste it to the docker container (eg with docker the command is : docker cp /host/path/target containerId:/file/path/within/container )

Yeah, that's what I did but anyhow seems to not be working, but at least they get recognized by iTop.
