### ISSUE TITLE
Resources (CSS, webfonts, etc) not being loaded (AWS-hosted)

### ISSUE THREAD

**Issue by matt-jay** [Super-Visions/docker-itop#18]
I have set up iTop using docker compose on an AWS EC2 instance. I can successfully connect to the interface (`UI.php` and `page-script.js` load fine), but all styling appears to be missing:

<img width="355" alt="image" src="https://github.com/Super-Visions/docker-itop/assets/1327393/41fd0b04-6b57-4004-9196-f641eb7085c7">

Some resource files (fonts, JS, CSS) appear to be failing to load after 20+ seconds:

<img width="1081" alt="image" src="https://github.com/Super-Visions/docker-itop/assets/1327393/605539d6-0b7a-473e-82ad-2abbb87937ed">

What I can observe for all of these resources is that while I run the site at <my_domain>:8010, these resources are requested from <some (Amazon?) IP>:8010/path/to/resource 

<img width="600" alt="image" src="https://github.com/Super-Visions/docker-itop/assets/1327393/cd71af5f-69c0-4d1d-b908-a34e56a46b61">

Has anyone experienced something similar, possibly in this specific context (AWS hosted), and can advise on steps to resolve the issue? Is this something that should be possible to fix in the iTop config (in terms of what host the resources are being requested from), or does this appear to be an issue with AWS magic?

**Comment by Hipska** [comment]
What is configured as `app_root_url` in the config file? And also see [this documentation](https://www.itophub.io/wiki/page?id=3_1_0:install:reverse_proxy).

**Comment by matt-jay** [comment]
@Hipska : What config file are you referring to? I can't find the `app_root_url` string in the documentation. At first glance, I found a reference to a config file in `conf/production`, but that one does not appear to have that setting:

```
root@13be8ba8a26e:/var/www/html/conf/production# cat config-itop.php
<?php

$MySettings = array(
	'db_host'    => $_ENV['DB_HOSTNAME'],
	'db_name'    => $_ENV['DB_ENV_MYSQL_DATABASE'],
	'db_user'    => $_ENV['DB_ENV_MYSQL_USER'],
	'db_pwd'     => $_ENV['DB_ENV_MYSQL_PASSWORD'],
	'db_subname' => $_ENV['DB_PREFIX'],
);

$MyModuleSettings = array();
$MyModules = array('addons' => array());
```

**Comment by Hipska** [comment]
It looks like you didn't run setup first. This needs to be done for every iTop instance before it can be used.

**Comment by matt-jay** [comment]
Sure looks like it! Apologies ... running setup fixed things.
