### ISSUE TITLE
Fatal error: Uncaught ConfigException: Syntax error in configuration file: file

### ISSUE THREAD

**Issue by github-cao** [Super-Visions/docker-itop#21]
By running like this, the following error occurs

```terminal
docker run -d -p 8088:80 --name=my-itop \
  -e DB_HOST=172.18.0.2 \
  -e DB_NAME=itop \
  -e DB_USER=itop \
  -e DB_PASSWORD=abc \
  supervisions/itop:latest
```

> Fatal error: Uncaught ConfigException: Syntax error in configuration file: file = /var/www/html/conf/production/config-itop.php, error = <tt>&lt;br /&gt; &lt;b&gt;Warning&lt;/b&gt;: Undefined array key &quot;DB_ENV_MYSQL_DATABASE&quot; in &lt;b&gt;/var/www/html/core/config.class.inc.php(2099) : eval()&apos;d code&lt;/b&gt; on line &lt;b&gt;5&lt;/b&gt;&lt;br /&gt; &lt;br /&gt; &lt;b&gt;Warning&lt;/b&gt;: Undefined array key &quot;DB_ENV_MYSQL_USER&quot; in &lt;b&gt;/var/www/html/core/config.class.inc.php(2099) : eval()&apos;d code&lt;/b&gt; on line &lt;b&gt;6&lt;/b&gt;&lt;br /&gt; &lt;br /&gt; &lt;b&gt;Warning&lt;/b&gt;: Undefined array key &quot;DB_ENV_MYSQL_PASSWORD&quot; in &lt;b&gt;/var/www/html/core/config.class.inc.php(2099) : eval()&apos;d code&lt;/b&gt; on line &lt;b&gt;7&lt;/b&gt;&lt;br /&gt;</tt> in /var/www/html/core/config.class.inc.php:2119
Stack trace: 
<span>#</span>0 /var/www/html/core/config.class.inc.php(2034): Config->Load() 
<span>#</span>1 /var/www/html/application/utils.inc.php(990): Config->__construct() 
<span>#</span>2 /var/www/html/sources/SessionTracker/SessionHandler.php(109): utils::GetConfig() 
<span>#</span>3 /var/www/html/sources/Application/Helper/Session.php(38): Combodo\iTop\SessionTracker\SessionHandler::session_set_save_handler() 
<span>#</span>4 /var/www/html/application/startup.inc.php(69): Combodo\iTop\Application\Helper\Session::Start() 
<span>#</span>5 /var/www/html/pages/UI.php(308): require_once('/var/www/html/a...') 
<span>#</span>6 {main} thrown in /var/www/html/core/config.class.inc.php on line 2119

> Fatal error: Uncaught ConfigException: Syntax error in configuration file: file = /var/www/html/conf/production/config-itop.php, error = <tt>&lt;br /&gt; &lt;b&gt;Warning&lt;/b&gt;: Undefined array key &quot;DB_ENV_MYSQL_DATABASE&quot; in &lt;b&gt;/var/www/html/core/config.class.inc.php(2099) : eval()&apos;d code&lt;/b&gt; on line &lt;b&gt;5&lt;/b&gt;&lt;br /&gt; &lt;br /&gt; &lt;b&gt;Warning&lt;/b&gt;: Undefined array key &quot;DB_ENV_MYSQL_USER&quot; in &lt;b&gt;/var/www/html/core/config.class.inc.php(2099) : eval()&apos;d code&lt;/b&gt; on line &lt;b&gt;6&lt;/b&gt;&lt;br /&gt; &lt;br /&gt; &lt;b&gt;Warning&lt;/b&gt;: Undefined array key &quot;DB_ENV_MYSQL_PASSWORD&quot; in &lt;b&gt;/var/www/html/core/config.class.inc.php(2099) : eval()&apos;d code&lt;/b&gt; on line &lt;b&gt;7&lt;/b&gt;&lt;br /&gt;</tt> in /var/www/html/core/config.class.inc.php:2119 
Stack trace: 
<span>#</span>0 /var/www/html/core/config.class.inc.php(2034): Config->Load() 
<span>#</span>1 /var/www/html/application/utils.inc.php(990): Config->__construct() 
<span>#</span>2 /var/www/html/core/log.class.inc.php(965): utils::GetConfig() 
<span>#</span>3 /var/www/html/core/log.class.inc.php(856): LogAPI::GetConfig()
<span>#</span>4 /var/www/html/core/log.class.inc.php(844): LogAPI::GetLogConfig()
<span>#</span>5 /var/www/html/core/log.class.inc.php(800): LogAPI::GetMinLogLevel()
<span>#</span>6 /var/www/html/core/log.class.inc.php(778): LogAPI::IsLogLevelEnabled()
<span>#</span>7 /var/www/html/core/log.class.inc.php(763): LogAPI::WriteLog()
<span>#</span>8 /var/www/html/core/log.class.inc.php(720): LogAPI::Log()
<span>#</span>9 /var/www/html/application/startup.inc.php(56): LogAPI::Error()
<span>#</span>10 [internal function]: {closure}()
<span>#</span>11 {main} thrown in /var/www/html/core/config.class.inc.php on line 2119

**Comment by Hipska** [comment]
Hi, first of all, you need to run the setup first in order to get started with iTop.
Secondly, if you want to get these variables filled in without linking to a DB container, you need to adapt the environment variables to be named like this: `DB_ENV_MYSQL_DATABASE`.

See details: https://github.com/Super-Visions/docker-itop/blob/96a816cde71f8bdab3f9403bb722d52b3bb41aeb/3.2/config-itop.php#L3-L9
