### ISSUE TITLE
web interface broken after recreating the docker image

### ISSUE THREAD

**Issue by stefan-sesser** [Super-Visions/docker-itop#3]
Hi,
At the moment I am facing some issues after recreating the docker image (vers. 2.7.4).
What I have done so far:
 - Setting up a maria db docker container
 - Setting up itop docker container
 - Configuring itop over the web interface 
 
Everything is working fine until I have **stopped and removed** the itop docker container.

After starting a new instance the web interface has some issues. I tried to reinstall itop with _http://localhost/setup_ path.
First attempt was to choose 'Upgrade an existing itop instance' to restore the data. Unfortunately this returned an error
![1](https://user-images.githubusercontent.com/44174625/115550919-ae756000-a2aa-11eb-87d2-1477c996fa36.png)

Second attempt was to create a new instance. Also this one resulted in an error:
_Error: found iTop tables into the database 'itop'. Please, try selecting another database instance or specify a prefix to prevent conflicting table names._

The only way I can restore my data was to create a backup and restore it afterwards. To get itop running I had to remove the db and rerun maria db and itop containers

Is this the way to go?
Thx

**Comment by Hipska** [comment]
Hi, this problem occurs because you didn't put the config file from previous install back. I usually mount the config file, but you can also replace it by doing `docker cp config.php my-itop:/var/www/html/conf/production/config-itop.php`.

**Comment by stefan-sesser** [comment]
Hi Hipska,
Many thanks to your comment. That really helped me out. 
Just to clarify the problem - root cause of this issue is due to not persisting the state of my maria db. Creating a mount for this container solved it. 
BTW: After installing itop via the browser ui, the `/var/www/html/conf/production/config-itop.php` file is readonly! So copying the file from the old to the new container will not work out of the box ;)
Thanks again
